export const ARTICLES_FETCH_REQUESTED = 'ARTICLES_FETCH_REQUESTED'
export const ARTICLES_FETCH_SUCCEEDED = 'ARTICLES_FETCH_SUCCEEDED'
export const ARTICLES_FETCH_FAILED = 'ARTICLES_FETCH_FAILED'
export const RESET_ARTICLES = 'RESET_ARTICLES'
