export const POSTS_FETCH_REQUESTED = 'POSTS_FETCH_REQUESTED'
export const POSTS_FETCH_SUCCEEDED = 'POSTS_FETCH_SUCCEEDED'
export const POSTS_FETCH_FAILED = 'POSTS_FETCH_FAILED'

export const POST_FETCH_REQUESTED = 'POST_FETCH_REQUESTED'
export const POST_FETCH_SUCCEEDED = 'POST_FETCH_SUCCEEDED'
export const POST_FETCH_FAILED = 'POST_FETCH_FAILED'

export const POST_CREATE_REQUESTED = 'POST_CREATE_REQUESTED'
export const POST_CREATE_SUCCEEDED = 'POST_CREATE_SUCCEEDED'
export const POST_CREATE_FAILED = 'POST_CREATE_FAILED'

export const POST_UPDATE_REQUESTED = 'POST_UPDATE_REQUESTED'
export const POST_UPDATE_SUCCEEDED = 'POST_UPDATE_SUCCEEDED'
export const POST_UPDATE_FAILED = 'POST_UPDATE_FAILED'

export const POST_DELETE_REQUESTED = 'POST_DELETE_REQUESTED'
export const POST_DELETE_SUCCEEDED = 'POST_DELETE_SUCCEEDED'
export const POST_DELETE_FAILED = 'POST_DELETE_FAILED'

export const RESET_POSTS = 'RESET_POSTS'
export const RESET_POST = 'RESET_POST'
