export const POSTS_FETCH_REQUESTED = 'POSTS_FETCH_REQUESTED'
export const POSTS_FETCH_SUCCEEDED = 'POSTS_FETCH_SUCCEEDED'
export const POSTS_FETCH_FAILED = 'POSTS_FETCH_FAILED'

export const POST_DELETE_REQUESTED = 'POST_DELETE_REQUESTED'
export const POST_DELETE_SUCCEEDED = 'POST_DELETE_SUCCEEDED'
export const POST_DELETE_FAILED = 'POST_DELETE_FAILED'

export const RESET_POSTS = 'RESET_POSTS'
