export const SET_COOKIES = 'SET_COOKIES'

export const AUTH_FETCH_REQUESTED = 'AUTH_FETCH_REQUESTED'
export const AUTH_FETCH_SUCCEEDED = 'AUTH_FETCH_SUCCEEDED'
export const AUTH_FETCH_FAILED = 'AUTH_FETCH_FAILED'

export const AUTH_LOGOUT_REQUESTED = 'AUTH_LOGOUT_REQUESTED'
export const AUTH_LOGOUT_SUCCEEDED = '  AUTH_LOGOUT_SUCCEEDED'
export const AUTH_LOGOUT_FAILED = '  AUTH_LOGOUT_FAILED'

export const APP_DATA_FETCH_REQUESTED = 'APP_DATA_FETCH_REQUESTED'
export const APP_DATA_FETCH_SUCCEEDED = 'APP_DATA_FETCH_SUCCEEDED'
export const APP_DATA_FETCH_FAILED = 'APP_DATA_FETCH_FAILED'

export const SOCKET_REQUESTED = 'SOCKET_REQUESTED'
export const SOCKET_SUCCEEDED = 'SOCKET_SUCCEEDED'
